version: '3'

services:
  web:
    image: atlas-webapp:v1.0
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/aws_poc
    ports:
      - "8000:8000"
    expose:
      - "8000"