version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/aws_poc
    ports:
      - "8000:8000"
    expose:
      - "8000"

networks:
  default:
    external:
      name: main_network