# Generated by Django 2.1 on 2018-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureMedianAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOG_NUMBER', models.TextField(max_length=45)),
                ('PRIMARY_CPT_CODE', models.TextField(max_length=45)),
                ('PRIMARY_CPT_GROUP', models.TextField(max_length=512)),
                ('PRIMARY_PROCEDURE_NAME', models.TextField(max_length=4096)),
                ('TOTAL_COST_SUM', models.FloatField()),
                ('RANK', models.IntegerField()),
                ('TOTAL_GROUP_REC', models.IntegerField()),
                ('AVG_PROCEDURE_COST', models.FloatField()),
                ('MEDIAN', models.FloatField()),
            ],
            options={
                'db_table': 'CPT_CODE_MEDIAN_AVG',
            },
        ),
        migrations.CreateModel(
            name='SuperGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_group', models.TextField(max_length=512)),
                ('primary_cpt_group', models.TextField(max_length=512)),
            ],
            options={
                'db_table': 'ABC_SUPERGROUP',
            },
        ),
    ]
