# Generated by Django 2.1 on 2018-10-24 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_connect', '0002_filehandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_appt_key', models.IntegerField()),
                ('patient_key', models.IntegerField()),
                ('personnel_key', models.IntegerField()),
                ('visit_type_key', models.IntegerField()),
                ('appt_start_datetime', models.DateTimeField()),
                ('appt_duration', models.IntegerField()),
                ('no_show_grouping', models.TextField()),
                ('appt_lag_grouping', models.TextField()),
                ('hhi_grouping', models.TextField()),
                ('distance_grouping', models.TextField()),
                ('payer_grouping', models.TextField()),
                ('inpatient_indicator', models.IntegerField()),
                ('prob_no_show', models.FloatField()),
                ('note', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 10, 24, 11, 7, 22, 178197))),
                ('create_user', models.TextField()),
            ],
            options={
                'db_table': 'rep"\\."appt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptkey', models.IntegerField()),
                ('deptname', models.TextField()),
                ('locationkey', models.IntegerField()),
                ('notindata', models.IntegerField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'dim"\\."dept',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FileHandler',
        ),
        migrations.DeleteModel(
            name='ProcedureMedianAvg',
        ),
        migrations.DeleteModel(
            name='SuperGroup',
        ),
    ]
