# Generated by Django 2.1 on 2018-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_connect', '0003_auto_20181024_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_key', models.IntegerField()),
                ('patient_prefix', models.TextField()),
                ('patient_first_name', models.TextField()),
                ('patient_middle_name', models.TextField()),
                ('patient_last_name', models.TextField()),
                ('patient_suffix', models.TextField()),
                ('patient_date_of_birth', models.DateField()),
                ('patient_ssn', models.TextField()),
                ('patient_phone', models.TextField()),
                ('patient_address1', models.TextField()),
                ('patient_address2', models.TextField()),
                ('patient_city', models.TextField()),
                ('patient_state', models.TextField()),
                ('patient_zip', models.TextField()),
                ('patient_longitude', models.FloatField()),
                ('patient_latitude', models.FloatField()),
                ('patient_gender_grpa1_key', models.IntegerField()),
                ('patient_race_grpa1_key', models.IntegerField()),
            ],
            options={
                'db_table': 'dim"\\."dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_key', models.IntegerField()),
                ('prefix', models.TextField()),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('last_name', models.TextField()),
                ('suffix', models.TextField()),
                ('npi', models.TextField()),
                ('job_code_key', models.IntegerField()),
                ('comp_type_key', models.IntegerField()),
                ('home_dept_key', models.IntegerField()),
                ('gender_key', models.IntegerField()),
                ('birth_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('term_date', models.DateTimeField()),
                ('term_reason_key', models.IntegerField()),
                ('primary_location_key', models.IntegerField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'dim"\\."personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_key', models.IntegerField()),
                ('practice_name', models.TextField()),
                ('practice_description', models.TextField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'dim"\\."practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type_key', models.IntegerField()),
                ('system_key', models.IntegerField()),
                ('visit_type_id', models.TextField()),
                ('visit_type_desc', models.TextField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'dim"\\."visit_type',
                'managed': False,
            },
        ),
    ]
