# Generated by Django 2.1 on 2018-10-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_connect', '0004_patient_personnel_practice_visittype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentreport',
            table='rep"."appt',
        ),
        migrations.AlterModelTable(
            name='department',
            table='dim"."dept',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='dim"."patient',
        ),
        migrations.AlterModelTable(
            name='personnel',
            table='dim"."personnel',
        ),
        migrations.AlterModelTable(
            name='practice',
            table='dim"."practice',
        ),
        migrations.AlterModelTable(
            name='visittype',
            table='dim"."visit_type',
        ),
    ]
